name: Deploy to Production

# Автоматический запуск при push в main или manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild all containers'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: alpine

    steps:
      # 1. Checkout кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Проверка окружения
      - name: Environment check
        run: |
          echo "🔍 Проверка окружения..."
          echo "Node.js: $(node --version)"
          echo "Python: $(python --version)"
          echo "Docker: $(docker --version)"
          echo "Docker Compose: $(docker compose version)"
          echo "Git: $(git --version)"

      # 3. Валидация Docker Compose конфигурации
      - name: Validate Docker Compose config
        run: |
          echo "🔍 Проверка docker-compose.yml..."
          docker compose -f docker-compose.yml config > /dev/null
          echo "✅ Docker Compose конфигурация валидна"

      # 4. Определение рабочей директории на хосте
      - name: Prepare deployment
        run: |
          echo "📂 Подготовка директории деплоя на хосте..."

          # Рабочая директория на хосте
          HOST_WORKDIR="/home/bessiaka/WORKSPACE/recording_life_system"

          # Проверка существования директории
          if docker run --rm -v /home/bessiaka:/home/bessiaka alpine test -d "$HOST_WORKDIR"; then
            echo "✅ Директория существует: $HOST_WORKDIR"
          else
            echo "📁 Создание директории: $HOST_WORKDIR"
            docker run --rm -v /home/bessiaka:/home/bessiaka alpine mkdir -p "$HOST_WORKDIR"
          fi

          # Сохраняем путь для следующих шагов
          echo "HOST_WORKDIR=$HOST_WORKDIR" >> $GITHUB_ENV

      # 5. Обновление кода на хосте
      - name: Update code on host
        run: |
          echo "🔄 Обновление кода на хосте..."

          # Копируем все файлы из checkout в директорию на хосте
          docker run --rm \
            -v "$(pwd)":/source \
            -v /home/bessiaka/WORKSPACE/recording_life_system:/dest \
            alpine sh -c "cp -r /source/. /dest/"

          echo "✅ Код обновлен на хосте"

      # 6. Сборка и деплой
      - name: Deploy to production
        run: |
          echo "🚀 Начало деплоя в production..."

          # Рабочая директория на хосте
          HOST_WORKDIR="/home/bessiaka/WORKSPACE/recording_life_system"

          # Остановка старых контейнеров
          echo "🛑 Остановка старых контейнеров..."
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOST_WORKDIR":"$HOST_WORKDIR" \
            -w "$HOST_WORKDIR" \
            docker/compose:latest \
            --env-file=.env.production down || true

          # Сборка новых образов
          echo "🔨 Сборка образов..."
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOST_WORKDIR":"$HOST_WORKDIR" \
            -w "$HOST_WORKDIR" \
            docker/compose:latest \
            --env-file=.env.production build --no-cache

          # Запуск контейнеров
          echo "🚀 Запуск контейнеров..."
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOST_WORKDIR":"$HOST_WORKDIR" \
            -w "$HOST_WORKDIR" \
            docker/compose:latest \
            --env-file=.env.production up -d

          # Ожидание готовности
          echo "⏳ Ожидание готовности сервисов..."
          sleep 10

          # Проверка статуса
          echo "✅ Проверка статуса контейнеров..."
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOST_WORKDIR":"$HOST_WORKDIR" \
            -w "$HOST_WORKDIR" \
            docker/compose:latest \
            --env-file=.env.production ps

      # 7. Health check
      - name: Health check
        run: |
          echo "🏥 Проверка работоспособности сервисов..."

          HOST_WORKDIR="/home/bessiaka/WORKSPACE/recording_life_system"

          # Проверка запущенных контейнеров
          RUNNING_CONTAINERS=$(docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOST_WORKDIR":"$HOST_WORKDIR" \
            -w "$HOST_WORKDIR" \
            docker/compose:latest \
            --env-file=.env.production ps --services --filter "status=running" | wc -l)

          TOTAL_SERVICES=$(docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOST_WORKDIR":"$HOST_WORKDIR" \
            -w "$HOST_WORKDIR" \
            docker/compose:latest \
            --env-file=.env.production ps --services | wc -l)

          echo "Запущено контейнеров: $RUNNING_CONTAINERS из $TOTAL_SERVICES"

          if [ "$RUNNING_CONTAINERS" -eq "$TOTAL_SERVICES" ]; then
            echo "✅ Все сервисы запущены успешно!"
          else
            echo "❌ Не все сервисы запущены. Проверьте логи:"
            docker run --rm \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v "$HOST_WORKDIR":"$HOST_WORKDIR" \
              -w "$HOST_WORKDIR" \
              docker/compose:latest \
              --env-file=.env.production logs --tail=50
            exit 1
          fi

      # 8. Очистка старых образов
      - name: Cleanup old images
        run: |
          echo "🧹 Очистка старых Docker образов..."
          docker image prune -f
          echo "✅ Очистка завершена"

      # 9. Итоговый отчет
      - name: Deployment summary
        run: |
          HOST_WORKDIR="/home/bessiaka/WORKSPACE/recording_life_system"

          echo "========================================="
          echo "✅ DEPLOYMENT COMPLETED SUCCESSFULLY"
          echo "========================================="
          echo ""
          echo "📊 Статус сервисов:"
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$HOST_WORKDIR":"$HOST_WORKDIR" \
            -w "$HOST_WORKDIR" \
            docker/compose:latest \
            --env-file=.env.production ps
          echo ""
          echo "💾 Использование дискового пространства:"
          docker system df
          echo ""
          echo "🎯 Deployment timestamp: $(date)"
          echo "========================================="
