name: Deploy to Production

# Автоматический запуск при push в main или manual trigger
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      force_rebuild:
        description: 'Force rebuild all containers'
        required: false
        default: 'false'

jobs:
  deploy:
    runs-on: alpine

    steps:
      # 1. Checkout кода из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Проверка окружения
      - name: Environment check
        run: |
          echo "🔍 Проверка окружения..."
          echo "Node.js: $(node --version)"
          echo "Python: $(python --version)"
          echo "Docker: $(docker --version)"
          echo "Docker Compose: $(docker compose version)"
          echo "Git: $(git --version)"

      # 3. Валидация Docker Compose конфигурации
      - name: Validate Docker Compose config
        run: |
          echo "🔍 Проверка docker-compose.yml..."
          docker compose -f docker-compose.yml config > /dev/null
          echo "✅ Docker Compose конфигурация валидна"

      # 4. Сборка и деплой
      - name: Deploy to production
        run: |
          echo "🚀 Начало деплоя в production..."

          # Остановка старых контейнеров
          echo "🛑 Остановка старых контейнеров..."
          docker compose --env-file=.env.production down || true

          # Сборка новых образов
          echo "🔨 Сборка образов..."
          docker compose --env-file=.env.production build --no-cache

          # Запуск контейнеров
          echo "🚀 Запуск контейнеров..."
          docker compose --env-file=.env.production up -d

          # Ожидание готовности
          echo "⏳ Ожидание готовности сервисов..."
          sleep 10

          # Проверка статуса
          echo "✅ Проверка статуса контейнеров..."
          docker compose --env-file=.env.production ps

      # 5. Health check
      - name: Health check
        run: |
          echo "🏥 Проверка работоспособности сервисов..."

          # Проверка запущенных контейнеров
          RUNNING_CONTAINERS=$(docker compose --env-file=.env.production ps --services --filter "status=running" | wc -l)
          TOTAL_SERVICES=$(docker compose --env-file=.env.production ps --services | wc -l)

          echo "Запущено контейнеров: $RUNNING_CONTAINERS из $TOTAL_SERVICES"

          if [ "$RUNNING_CONTAINERS" -eq "$TOTAL_SERVICES" ]; then
            echo "✅ Все сервисы запущены успешно!"
          else
            echo "❌ Не все сервисы запущены. Проверьте логи:"
            docker compose --env-file=.env.production logs --tail=50
            exit 1
          fi

      # 6. Очистка старых образов
      - name: Cleanup old images
        run: |
          echo "🧹 Очистка старых Docker образов..."
          docker image prune -f
          echo "✅ Очистка завершена"

      # 7. Итоговый отчет
      - name: Deployment summary
        run: |
          echo "========================================="
          echo "✅ DEPLOYMENT COMPLETED SUCCESSFULLY"
          echo "========================================="
          echo ""
          echo "📊 Статус сервисов:"
          docker compose --env-file=.env.production ps
          echo ""
          echo "💾 Использование дискового пространства:"
          docker system df
          echo ""
          echo "🎯 Deployment timestamp: $(date)"
          echo "========================================="
